### ISSUE TITLE
Training on DAVIS dataset

### ISSUE THREAD

**Issue by AngelTang190** [wjn922/ReferFormer#22]
Hi, I am having CUDA OOM issue when I train using DAVIS dataset, may I know what can solve the issue? The following is the result of error:

Size of attn: torch.Size([120, 24, 49, 49])
Size of relative_position_bias.unsqueeze(0): torch.Size([1, 24, 49, 49])

Size of attn: torch.Size([120, 24, 49, 49])
Size of v: torch.Size([120, 24, 49, 32])

Size of attn: torch.Size([120, 24, 49, 49])
Size of v: torch.Size([120, 24, 49, 32])
Traceback (most recent call last):
  File "main.py", line 250, in <module>
    main(args)
  File "main.py", line 200, in main
    train_stats = train_one_epoch(
  File "/home/fyp-student/PycharmProjects/ReferringImageSegmentationTraining/ReferFormer/engine.py", line 43, in train_one_epoch
    outputs = model(samples, captions, targets) #forward() in Referformer Class under referformer.py
  File "/home/fyp-student/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fyp-student/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/fyp-student/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fyp-student/PycharmProjects/ReferringImageSegmentationTraining/ReferFormer/models/referformer.py", line 207, in forward
    features, pos = self.backbone(samples) 
  File "/home/fyp-student/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fyp-student/PycharmProjects/ReferringImageSegmentationTraining/ReferFormer/models/swin_transformer.py", line 680, in forward
    xs = self[0](tensor_list)
  File "/home/fyp-student/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fyp-student/PycharmProjects/ReferringImageSegmentationTraining/ReferFormer/models/swin_transformer.py", line 644, in forward
    xs = self.body(tensor_list.tensors)
  File "/home/fyp-student/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fyp-student/PycharmProjects/ReferringImageSegmentationTraining/ReferFormer/models/swin_transformer.py", line 621, in forward
    x_out, H, W, x, Wh, Ww = layer(x, Wh, Ww)
  File "/home/fyp-student/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fyp-student/PycharmProjects/ReferringImageSegmentationTraining/ReferFormer/models/swin_transformer.py", line 406, in forward
    x = blk(x, attn_mask)
  File "/home/fyp-student/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fyp-student/PycharmProjects/ReferringImageSegmentationTraining/ReferFormer/models/swin_transformer.py", line 248, in forward
    attn_windows = self.attn(x_windows, mask=attn_mask)  # nW*B, window_size*window_size, C
  File "/home/fyp-student/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fyp-student/PycharmProjects/ReferringImageSegmentationTraining/ReferFormer/models/swin_transformer.py", line 162, in forward
    attn_v = torch.matmul(attn, v)
RuntimeError: CUDA out of memory. Tried to allocate 18.00 MiB (GPU 0; 10.75 GiB total capacity; 8.61 GiB already allocated; 21.69 MiB free; 8.97 GiB reserved in total by PyTorch)

I tried to run the line: ./scripts/dist_train_test_davis.sh davis_dirs/swin_large pretrained_weights/swin_large_pretrained.pth --backbone swin_l_p4w7.

The CUDA OOM error pops up after a few iteration of  matrix multiplication between attn and v. May I know what can solve this issue? Thank you,

@iFighting @wjn922

**Comment by AngelTang190** [comment]
The CUDA OOM error can be eliminated by reducing the training batch size to 1, reducing args.max_size in main.py and max_size in make_coco_transforms() of davis.py. If OOM error is met in inference, the value in T.Resize() value can be reduced.
